package testes

import (
	"fmt"
)

// DemonstrarSubtestes demonstra o uso de subtestes com test.Run
func DemonstrarSubtestes() {
	fmt.Println("--- SUBTESTES ---")
	fmt.Println("Subtestes permitem organizar testes relacionados dentro de uma função.")
	fmt.Println("Eles são criados usando test.Run() e podem ser executados independentemente.\n")

	fmt.Println("Por que usar subtestes?")
	fmt.Println("  - Organizam testes relacionados logicamente")
	fmt.Println("  - Permitem executar subtestes específicos")
	fmt.Println("  - Facilitam setup e teardown por subteste")
	fmt.Println("  - Permitem execução paralela quando apropriado")
	fmt.Println("  - Melhoram a organização de table-driven tests\n")

	fmt.Println("Estrutura básica:")
	fmt.Println("  func TestFuncao(t *testing.T) {")
	fmt.Println("      t.Run(\"Nome do subteste\", func(t *testing.T) {")
	fmt.Println("          // Código do subteste")
	fmt.Println("      })")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 1: Subtestes básicos")
	fmt.Println("Organizando testes relacionados:\n")

	fmt.Println("  func TestCalculadora(t *testing.T) {")
	fmt.Println("      t.Run(\"Soma\", func(t *testing.T) {")
	fmt.Println("          resultado := soma(2, 3)")
	fmt.Println("          if resultado != 5 {")
	fmt.Println("              t.Error(\"Soma falhou\")")
	fmt.Println("          }")
	fmt.Println("      })")
	fmt.Println()
	fmt.Println("      t.Run(\"Subtracao\", func(t *testing.T) {")
	fmt.Println("          resultado := subtracao(5, 2)")
	fmt.Println("          if resultado != 3 {")
	fmt.Println("              t.Error(\"Subtracao falhou\")")
	fmt.Println("          }")
	fmt.Println("      })")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 2: Subtestes com table-driven tests")
	fmt.Println("Combinando subtestes com tabelas de cenários:\n")

	fmt.Println("  func TestValidacao(t *testing.T) {")
	fmt.Println("      cenarios := []struct{")
	fmt.Println("          nome     string")
	fmt.Println("          entrada  string")
	fmt.Println("          esperado bool")
	fmt.Println("      }{")
	fmt.Println("          {\"email válido\", \"teste@exemplo.com\", true},")
	fmt.Println("          {\"email inválido\", \"invalido\", false},")
	fmt.Println("      }")
	fmt.Println()
	fmt.Println("      for _, cenario := range cenarios {")
	fmt.Println("          t.Run(cenario.nome, func(t *testing.T) {")
	fmt.Println("              resultado := validarEmail(cenario.entrada)")
	fmt.Println("              if resultado != cenario.esperado {")
	fmt.Println("                  t.Errorf(\"Resultado %v, esperado %v\", resultado, cenario.esperado)")
	fmt.Println("              }")
	fmt.Println("          })")
	fmt.Println("      }")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 3: Subtestes com execução paralela")
	fmt.Println("Usando t.Parallel() para executar subtestes simultaneamente:\n")

	fmt.Println("  func TestOperacoes(t *testing.T) {")
	fmt.Println("      t.Run(\"Operacao A\", func(t *testing.T) {")
	fmt.Println("          t.Parallel()")
	fmt.Println("          // Código do teste")
	fmt.Println("      })")
	fmt.Println()
	fmt.Println("      t.Run(\"Operacao B\", func(t *testing.T) {")
	fmt.Println("          t.Parallel()")
	fmt.Println("          // Código do teste")
	fmt.Println("      })")
	fmt.Println("  }\n")

	fmt.Println("Vantagens de usar t.Parallel():")
	fmt.Println("  ✓ Testes executam mais rápido")
	fmt.Println("  ✓ Melhor uso de recursos quando há muitos testes")
	fmt.Println("  ✓ Útil para testes de I/O ou rede")
	fmt.Println("  ⚠️  Cuidado: testes devem ser independentes\n")

	fmt.Println("Exemplo 4: Subtestes com setup e teardown")
	fmt.Println("Configuração específica para cada subteste:\n")

	fmt.Println("  func TestComSetup(t *testing.T) {")
	fmt.Println("      t.Run(\"Caso 1\", func(t *testing.T) {")
	fmt.Println("          // Setup específico")
	fmt.Println("          recurso := criarRecurso()")
	fmt.Println("          defer limparRecurso(recurso)")
	fmt.Println()
	fmt.Println("          // Teste")
	fmt.Println("          resultado := usarRecurso(recurso)")
	fmt.Println("          if resultado != esperado {")
	fmt.Println("              t.Error(\"Falhou\")")
	fmt.Println("          }")
	fmt.Println("      })")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 5: Executando subtestes específicos")
	fmt.Println("Você pode executar apenas um subteste:\n")

	fmt.Println("  go test -run TestFuncao/SubtesteEspecifico")
	fmt.Println("  go test -run TestFuncao/Subteste")
	fmt.Println("  go test -run TestFuncao  // Executa todos os subtestes\n")

	fmt.Println("Diferença entre subtestes e testes separados:")
	fmt.Println("  Subtestes (test.Run):")
	fmt.Println("    ✓ Organizados logicamente dentro de uma função")
	fmt.Println("    ✓ Compartilham setup comum")
	fmt.Println("    ✓ Podem ser executados seletivamente")
	fmt.Println("    ✓ Úteis para table-driven tests\n")

	fmt.Println("  Testes separados (Test*):")
	fmt.Println("    ✓ Completamente independentes")
	fmt.Println("    ✓ Cada um tem seu próprio setup")
	fmt.Println("    ✓ Mais fácil de identificar qual falhou")
	fmt.Println("    ✓ Úteis para testes não relacionados\n")

	fmt.Println("Quando usar cada abordagem:")
	fmt.Println("  Use subtestes quando:")
	fmt.Println("    - Testes estão relacionados logicamente")
	fmt.Println("    - Compartilham setup comum")
	fmt.Println("    - Quer executar grupo de testes juntos")
	fmt.Println("    - Usando table-driven tests\n")

	fmt.Println("  Use testes separados quando:")
	fmt.Println("    - Testes são completamente independentes")
	fmt.Println("    - Cada teste precisa de setup diferente")
	fmt.Println("    - Quer isolamento total entre testes\n")

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - Nomes de subtestes devem ser descritivos")
	fmt.Println("  - Use t.Parallel() apenas se testes forem independentes")
	fmt.Println("  - Cuidado com estado compartilhado em testes paralelos")
	fmt.Println("  - Subtestes são executados sequencialmente por padrão")
	fmt.Println("  - Use -run para executar subtestes específicos")
	fmt.Println("  - Combine subtestes com table-driven tests para melhor organização")
	fmt.Println("  - Cada subteste recebe seu próprio *testing.T")
	fmt.Println()
}
