package testes

import (
	"fmt"
)

// DemonstrarTestesTabela demonstra o padrão table-driven tests
func DemonstrarTestesTabela() {
	fmt.Println("--- TESTES COM TABELA (TABLE-DRIVEN TESTS) ---")
	fmt.Println("Table-driven tests são testes que usam uma estrutura de dados")
	fmt.Println("(geralmente um slice de structs) para definir múltiplos cenários de teste.\n")

	fmt.Println("Por que usar table-driven tests?")
	fmt.Println("  - Fácil adicionar novos casos de teste")
	fmt.Println("  - Código DRY (Don't Repeat Yourself)")
	fmt.Println("  - Legibilidade melhorada")
	fmt.Println("  - Testes organizados e fáceis de manter")
	fmt.Println("  - Permite testar muitos cenários rapidamente\n")

	fmt.Println("Estrutura básica:")
	fmt.Println("  1. Definir struct com campos de entrada e saída esperada")
	fmt.Println("  2. Criar slice com múltiplos cenários")
	fmt.Println("  3. Iterar sobre cenários com range")
	fmt.Println("  4. Executar função e comparar resultado\n")

	fmt.Println("Exemplo 1: Estrutura básica de table-driven test")
	fmt.Println("Testando função de soma com múltiplos cenários:\n")

	fmt.Println("  type cenarioTeste struct {")
	fmt.Println("      entradaA   int")
	fmt.Println("      entradaB   int")
	fmt.Println("      esperado   int")
	fmt.Println("      descricao  string")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func TestSoma(t *testing.T) {")
	fmt.Println("      cenarios := []cenarioTeste{")
	fmt.Println("          {entradaA: 1, entradaB: 2, esperado: 3, descricao: \"números positivos\"},")
	fmt.Println("          {entradaA: -1, entradaB: 1, esperado: 0, descricao: \"número negativo e positivo\"},")
	fmt.Println("          {entradaA: 0, entradaB: 0, esperado: 0, descricao: \"zeros\"},")
	fmt.Println("      }")
	fmt.Println()
	fmt.Println("      for _, cenario := range cenarios {")
	fmt.Println("          resultado := soma(cenario.entradaA, cenario.entradaB)")
	fmt.Println("          if resultado != cenario.esperado {")
	fmt.Println("              t.Errorf(\"Cenário '%s': resultado %d, esperado %d\",")
	fmt.Println("                  cenario.descricao, resultado, cenario.esperado)")
	fmt.Println("          }")
	fmt.Println("      }")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 2: Table-driven test com strings")
	fmt.Println("Testando função de validação de email:\n")

	fmt.Println("  type cenarioEmail struct {")
	fmt.Println("      email      string")
	fmt.Println("      esperado   bool")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func TestValidarEmail(t *testing.T) {")
	fmt.Println("      cenarios := []cenarioEmail{")
	fmt.Println("          {email: \"teste@exemplo.com\", esperado: true},")
	fmt.Println("          {email: \"invalido\", esperado: false},")
	fmt.Println("          {email: \"@exemplo.com\", esperado: false},")
	fmt.Println("      }")
	fmt.Println()
	fmt.Println("      for _, cenario := range cenarios {")
	fmt.Println("          resultado := validarEmail(cenario.email)")
	fmt.Println("          if resultado != cenario.esperado {")
	fmt.Println("              t.Errorf(\"Email '%s': resultado %v, esperado %v\",")
	fmt.Println("                  cenario.email, resultado, cenario.esperado)")
	fmt.Println("          }")
	fmt.Println("      }")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 3: Table-driven test com múltiplos campos")
	fmt.Println("Testando função que processa múltiplas entradas:\n")

	fmt.Println("  type cenarioProcessamento struct {")
	fmt.Println("      nome       string")
	fmt.Println("      idade      int")
	fmt.Println("      ativo      bool")
	fmt.Println("      esperado   string")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func TestProcessarUsuario(t *testing.T) {")
	fmt.Println("      cenarios := []cenarioProcessamento{")
	fmt.Println("          {nome: \"João\", idade: 25, ativo: true, esperado: \"João-25-ativo\"},")
	fmt.Println("          {nome: \"Maria\", idade: 30, ativo: false, esperado: \"Maria-30-inativo\"},")
	fmt.Println("      }")
	fmt.Println()
	fmt.Println("      for indice, cenario := range cenarios {")
	fmt.Println("          resultado := processarUsuario(cenario.nome, cenario.idade, cenario.ativo)")
	fmt.Println("          if resultado != cenario.esperado {")
	fmt.Println("              t.Errorf(\"Cenário %d: resultado '%s', esperado '%s'\",")
	fmt.Println("                  indice, resultado, cenario.esperado)")
	fmt.Println("          }")
	fmt.Println("      }")
	fmt.Println("  }\n")

	fmt.Println("Vantagens do table-driven tests:")
	fmt.Println("  ✓ Fácil adicionar novos casos: apenas adicione ao slice")
	fmt.Println("  ✓ Código mais limpo: sem repetição de lógica de teste")
	fmt.Println("  ✓ Melhor legibilidade: todos os casos visíveis de uma vez")
	fmt.Println("  ✓ Manutenção simplificada: mudanças em um lugar")
	fmt.Println("  ✓ Testes rápidos: muitos casos em uma função\n")

	fmt.Println("Quando usar table-driven tests:")
	fmt.Println("  - Quando você tem múltiplos casos de teste similares")
	fmt.Println("  - Quando a lógica de teste é a mesma para todos os casos")
	fmt.Println("  - Quando quer testar diferentes combinações de entrada")
	fmt.Println("  - Quando precisa de muitos casos de teste\n")

	fmt.Println("Exemplo 4: Table-driven test com casos de erro")
	fmt.Println("Testando tratamento de erros:\n")

	fmt.Println("  type cenarioErro struct {")
	fmt.Println("      entrada    int")
	fmt.Println("      esperaErro bool")
	fmt.Println("      mensagem   string")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func TestDivisao(t *testing.T) {")
	fmt.Println("      cenarios := []cenarioErro{")
	fmt.Println("          {entrada: 10, esperaErro: false, mensagem: \"divisão válida\"},")
	fmt.Println("          {entrada: 0, esperaErro: true, mensagem: \"divisão por zero\"},")
	fmt.Println("      }")
	fmt.Println()
	fmt.Println("      for _, cenario := range cenarios {")
	fmt.Println("          _, erro := dividir(100, cenario.entrada)")
	fmt.Println("          temErro := erro != nil")
	fmt.Println("          if temErro != cenario.esperaErro {")
	fmt.Println("              t.Errorf(\"Cenário '%s': erro esperado %v, recebido %v\",")
	fmt.Println("                  cenario.mensagem, cenario.esperaErro, temErro)")
	fmt.Println("          }")
	fmt.Println("      }")
	fmt.Println("  }\n")

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - Use structs descritivas para os cenários")
	fmt.Println("  - Inclua campo 'descricao' ou 'nome' para identificar casos")
	fmt.Println("  - Use mensagens de erro claras com informações do cenário")
	fmt.Println("  - Considere usar t.Run() para executar cada caso como subteste")
	fmt.Println("  - Mantenha a estrutura simples e legível")
	fmt.Println("  - Agrupe casos relacionados na mesma tabela")
	fmt.Println()
}
