package http

import (
	"fmt"
)

// DemonstrarMetodosHTTP demonstra os métodos HTTP básicos
func DemonstrarMetodosHTTP() {
	fmt.Println("--- MÉTODOS HTTP ---")
	fmt.Println("HTTP define vários métodos (verbos) para indicar a ação desejada.")
	fmt.Println("Os mais comuns são GET, POST, PUT e DELETE.\n")

	fmt.Println("Por que diferentes métodos HTTP?")
	fmt.Println("  - Cada método tem um propósito específico")
	fmt.Println("  - Facilita organização e entendimento da API")
	fmt.Println("  - Permite diferentes comportamentos para a mesma rota")
	fmt.Println("  - Segue padrões RESTful")
	fmt.Println("  - Melhora semântica e clareza do código\n")

	fmt.Println("Métodos HTTP básicos:")
	fmt.Println("  - GET: Buscar/ler dados (não modifica estado)")
	fmt.Println("  - POST: Criar novos recursos")
	fmt.Println("  - PUT: Atualizar recursos existentes")
	fmt.Println("  - DELETE: Deletar recursos\n")

	fmt.Println("Exemplo 1: Método GET")
	fmt.Println("GET é usado para buscar informações sem modificar dados:\n")

	fmt.Println("  http.HandleFunc(\"/usuarios\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      if requisicao.Method != http.MethodGet {")
	fmt.Println("          http.Error(escritorResposta, \"Método não permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Lista de usuários\")")
	fmt.Println("  })\n")

	fmt.Println("Exemplo 2: Método GET com query parameters")
	fmt.Println("Lendo parâmetros da URL:\n")

	fmt.Println("  http.HandleFunc(\"/buscar\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      if requisicao.Method != http.MethodGet {")
	fmt.Println("          http.Error(escritorResposta, \"Método não permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      nome := requisicao.URL.Query().Get(\"nome\")")
	fmt.Println("      idade := requisicao.URL.Query().Get(\"idade\")")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Nome: %s, Idade: %s\", nome, idade)")
	fmt.Println("  })")
	fmt.Println("  // Uso: /buscar?nome=João&idade=30\n")

	fmt.Println("Exemplo 3: Método POST")
	fmt.Println("POST é usado para criar novos recursos, geralmente enviando dados no body:\n")

	fmt.Println("  http.HandleFunc(\"/usuarios\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      if requisicao.Method != http.MethodPost {")
	fmt.Println("          http.Error(escritorResposta, \"Método não permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      corpoRequisicao, erro := io.ReadAll(requisicao.Body)")
	fmt.Println("      defer requisicao.Body.Close()")
	fmt.Println("      if erro != nil {")
	fmt.Println("          http.Error(escritorResposta, \"Erro ao ler body\", http.StatusBadRequest)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Dados recebidos: %s\", string(corpoRequisicao))")
	fmt.Println("  })\n")

	fmt.Println("Exemplo 4: Método POST com JSON")
	fmt.Println("Recebendo e processando dados JSON:\n")

	fmt.Println("  http.HandleFunc(\"/criar\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      if requisicao.Method != http.MethodPost {")
	fmt.Println("          http.Error(escritorResposta, \"Método não permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      var dados map[string]interface{}")
	fmt.Println("      erro := json.NewDecoder(requisicao.Body).Decode(&dados)")
	fmt.Println("      defer requisicao.Body.Close()")
	fmt.Println("      if erro != nil {")
	fmt.Println("          http.Error(escritorResposta, \"JSON inválido\", http.StatusBadRequest)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      escritorResposta.Header().Set(\"Content-Type\", \"application/json\")")
	fmt.Println("      json.NewEncoder(escritorResposta).Encode(map[string]string{\"status\": \"criado\"})")
	fmt.Println("  })\n")

	fmt.Println("Exemplo 5: Método PUT")
	fmt.Println("PUT é usado para atualizar recursos existentes:\n")

	fmt.Println("  http.HandleFunc(\"/usuarios/atualizar\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      if requisicao.Method != http.MethodPut {")
	fmt.Println("          http.Error(escritorResposta, \"Método não permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      corpoRequisicao, _ := io.ReadAll(requisicao.Body)")
	fmt.Println("      defer requisicao.Body.Close()")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Atualizando com: %s\", string(corpoRequisicao))")
	fmt.Println("  })\n")

	fmt.Println("Exemplo 6: Método DELETE")
	fmt.Println("DELETE é usado para remover recursos:\n")

	fmt.Println("  http.HandleFunc(\"/usuarios/deletar\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      if requisicao.Method != http.MethodDelete {")
	fmt.Println("          http.Error(escritorResposta, \"Método não permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      id := requisicao.URL.Query().Get(\"id\")")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Deletando usuário ID: %s\", id)")
	fmt.Println("  })\n")

	fmt.Println("Exemplo 7: Retornando JSON")
	fmt.Println("Enviando resposta em formato JSON:\n")

	fmt.Println("  http.HandleFunc(\"/dados\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      dados := map[string]string{")
	fmt.Println("          \"nome\": \"João\",")
	fmt.Println("          \"idade\": \"30\",")
	fmt.Println("      }")
	fmt.Println("      escritorResposta.Header().Set(\"Content-Type\", \"application/json\")")
	fmt.Println("      json.NewEncoder(escritorResposta).Encode(dados)")
	fmt.Println("  })\n")

	fmt.Println("Exemplo 8: Status codes HTTP")
	fmt.Println("Definindo códigos de status apropriados:\n")

	fmt.Println("  http.HandleFunc(\"/sucesso\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      escritorResposta.WriteHeader(http.StatusOK)")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Sucesso\")")
	fmt.Println("  })")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/nao-encontrado\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      escritorResposta.WriteHeader(http.StatusNotFound)")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Não encontrado\")")
	fmt.Println("  })")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/erro\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      http.Error(escritorResposta, \"Erro interno\", http.StatusInternalServerError)")
	fmt.Println("  })\n")

	fmt.Println("Códigos de status comuns:")
	fmt.Println("  - 200 OK: Requisição bem-sucedida")
	fmt.Println("  - 201 Created: Recurso criado com sucesso")
	fmt.Println("  - 400 Bad Request: Requisição inválida")
	fmt.Println("  - 404 Not Found: Recurso não encontrado")
	fmt.Println("  - 405 Method Not Allowed: Método não permitido")
	fmt.Println("  - 500 Internal Server Error: Erro no servidor\n")

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - Sempre verifique o método da requisição antes de processar")
	fmt.Println("  - Use http.MethodGet, http.MethodPost, etc. (não strings literais)")
	fmt.Println("  - Sempre feche o Body da requisição com defer")
	fmt.Println("  - Defina Content-Type antes de escrever no ResponseWriter")
	fmt.Println("  - Use status codes apropriados para cada situação")
	fmt.Println("  - GET não deve modificar estado do servidor")
	fmt.Println("  - POST/PUT geralmente enviam dados no body")
	fmt.Println("  - DELETE geralmente usa ID na URL ou query params")
	fmt.Println()
}
