package web

import (
	"fmt"
)

// DemonstrarHTMLBasico demonstra os conceitos básicos de HTML
func DemonstrarHTMLBasico() {
	fmt.Println("--- HTML BÁSICO ---")
	fmt.Println("HTML (HyperText Markup Language) é a linguagem de marcação usada")
	fmt.Println("para estruturar conteúdo em páginas web.")
	fmt.Println()

	fmt.Println("Por que usar HTML?")
	fmt.Println("  - Define a estrutura e semântica do conteúdo")
	fmt.Println("  - Padrão universal para páginas web")
	fmt.Println("  - Base para CSS e JavaScript")
	fmt.Println("  - Acessível por navegadores e leitores de tela")
	fmt.Println("  - Essencial para qualquer aplicação web")
	fmt.Println()

	fmt.Println("Estrutura básica de um documento HTML:")
	fmt.Println("  <!DOCTYPE html>")
	fmt.Println("  <html>")
	fmt.Println("    <head>")
	fmt.Println("      <!-- Metadados e configurações -->")
	fmt.Println("    </head>")
	fmt.Println("    <body>")
	fmt.Println("      <!-- Conteúdo visível -->")
	fmt.Println("    </body>")
	fmt.Println("  </html>")
	fmt.Println()

	fmt.Println("Exemplo 1: Estrutura mínima de HTML")
	fmt.Println("Um documento HTML básico:")
	fmt.Println()

	fmt.Println("  <!DOCTYPE html>")
	fmt.Println("  <html lang=\"pt-BR\">")
	fmt.Println("  <head>")
	fmt.Println("      <meta charset=\"UTF-8\">")
	fmt.Println("      <title>Minha Página</title>")
	fmt.Println("  </head>")
	fmt.Println("  <body>")
	fmt.Println("      <h1>Título Principal</h1>")
	fmt.Println("      <p>Parágrafo de texto</p>")
	fmt.Println("  </body>")
	fmt.Println("  </html>")
	fmt.Println()

	fmt.Println("Exemplo 2: Tags essenciais")
	fmt.Println("Tags mais comuns em HTML:")
	fmt.Println()

	fmt.Println("  <h1> a <h6> - Títulos (h1 é o mais importante)")
	fmt.Println("  <p> - Parágrafo")
	fmt.Println("  <div> - Divisão genérica de conteúdo")
	fmt.Println("  <span> - Texto inline genérico")
	fmt.Println("  <a href=\"url\"> - Link")
	fmt.Println("  <img src=\"imagem.jpg\" alt=\"descrição\"> - Imagem")
	fmt.Println("  <button> - Botão")
	fmt.Println("  <input> - Campo de entrada")
	fmt.Println("  <ul> e <li> - Lista não ordenada")
	fmt.Println("  <ol> e <li> - Lista ordenada")
	fmt.Println()

	fmt.Println("Exemplo 3: Atributos básicos")
	fmt.Println("Atributos fornecem informações adicionais sobre elementos:")
	fmt.Println()

	fmt.Println("  <a href=\"https://exemplo.com\">Link</a>")
	fmt.Println("  <!-- href define o destino do link -->")
	fmt.Println()
	fmt.Println("  <img src=\"foto.jpg\" alt=\"Descrição da foto\">")
	fmt.Println("  <!-- src define origem, alt define texto alternativo -->")
	fmt.Println()
	fmt.Println("  <div class=\"container\">Conteúdo</div>")
	fmt.Println("  <!-- class permite aplicar estilos CSS -->")
	fmt.Println()
	fmt.Println("  <p id=\"paragrafo-unico\">Texto</p>")
	fmt.Println("  <!-- id identifica elemento único -->")
	fmt.Println()

	fmt.Println("Exemplo 4: Estrutura semântica")
	fmt.Println("HTML5 introduziu tags semânticas para melhor organização:")
	fmt.Println()

	fmt.Println("  <header> - Cabeçalho da página")
	fmt.Println("  <nav> - Navegação")
	fmt.Println("  <main> - Conteúdo principal")
	fmt.Println("  <article> - Artigo independente")
	fmt.Println("  <section> - Seção de conteúdo")
	fmt.Println("  <aside> - Conteúdo lateral")
	fmt.Println("  <footer> - Rodapé")
	fmt.Println()

	fmt.Println("Exemplo 5: Formulário básico")
	fmt.Println("Criando um formulário simples:")
	fmt.Println()

	fmt.Println("  <form action=\"/enviar\" method=\"POST\">")
	fmt.Println("      <label for=\"nome\">Nome:</label>")
	fmt.Println("      <input type=\"text\" id=\"nome\" name=\"nome\" required>")
	fmt.Println("      <br>")
	fmt.Println("      <label for=\"email\">Email:</label>")
	fmt.Println("      <input type=\"email\" id=\"email\" name=\"email\" required>")
	fmt.Println("      <br>")
	fmt.Println("      <button type=\"submit\">Enviar</button>")
	fmt.Println("  </form>")
	fmt.Println()

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - Sempre use <!DOCTYPE html> no início")
	fmt.Println("  - Defina charset UTF-8 no <head>")
	fmt.Println("  - Use tags semânticas quando apropriado")
	fmt.Println("  - Atributo 'alt' é obrigatório em imagens")
	fmt.Println("  - Use 'id' para elementos únicos, 'class' para grupos")
	fmt.Println("  - Valide HTML antes de publicar")
	fmt.Println("  - HTML define estrutura, não aparência (use CSS)")
	fmt.Println()
}
