package web

import (
	"fmt"
)

// DemonstrarIntegracao demonstra como HTML, CSS e JavaScript trabalham juntos
func DemonstrarIntegracao() {
	fmt.Println("--- INTEGRAÇÃO HTML, CSS E JAVASCRIPT ---")
	fmt.Println("HTML, CSS e JavaScript trabalham juntos para criar páginas web completas.")
	fmt.Println("Cada um tem um papel específico na construção de uma aplicação web.")
	fmt.Println()

	fmt.Println("Como os três trabalham juntos:")
	fmt.Println("  - HTML: Define a estrutura e conteúdo")
	fmt.Println("  - CSS: Define a aparência visual")
	fmt.Println("  - JavaScript: Adiciona comportamento e interatividade")
	fmt.Println("  - Todos são servidos pelo servidor HTTP")
	fmt.Println("  - Navegador combina os três para renderizar a página")
	fmt.Println()

	fmt.Println("Fluxo completo de uma página web:")
	fmt.Println("  1. Cliente faz requisição HTTP para o servidor")
	fmt.Println("  2. Servidor responde com arquivo HTML")
	fmt.Println("  3. Navegador lê HTML e encontra referências a CSS e JS")
	fmt.Println("  4. Navegador faz requisições adicionais para CSS e JS")
	fmt.Println("  5. Navegador combina HTML + CSS + JS e renderiza página")
	fmt.Println("  6. JavaScript pode fazer requisições adicionais (AJAX)")
	fmt.Println()

	fmt.Println("Exemplo 1: Estrutura completa de uma página")
	fmt.Println("HTML vinculando CSS e JavaScript:")
	fmt.Println()

	fmt.Println("  <!DOCTYPE html>")
	fmt.Println("  <html lang=\"pt-BR\">")
	fmt.Println("  <head>")
	fmt.Println("      <meta charset=\"UTF-8\">")
	fmt.Println("      <title>Página Completa</title>")
	fmt.Println("      <link rel=\"stylesheet\" href=\"/static/estilo.css\">")
	fmt.Println("  </head>")
	fmt.Println("  <body>")
	fmt.Println("      <h1 id=\"titulo\">Título</h1>")
	fmt.Println("      <button id=\"botao\">Clique Aqui</button>")
	fmt.Println("      <script src=\"/static/script.js\"></script>")
	fmt.Println("  </body>")
	fmt.Println("  </html>")
	fmt.Println()

	fmt.Println("Exemplo 2: CSS estilizando elementos HTML")
	fmt.Println("CSS aplicando estilos aos elementos:")
	fmt.Println()

	fmt.Println("  /* estilo.css */")
	fmt.Println("  #titulo {")
	fmt.Println("      color: blue;")
	fmt.Println("      font-size: 24px;")
	fmt.Println("      text-align: center;")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  #botao {")
	fmt.Println("      background-color: green;")
	fmt.Println("      color: white;")
	fmt.Println("      padding: 10px 20px;")
	fmt.Println("      border: none;")
	fmt.Println("      cursor: pointer;")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("Exemplo 3: JavaScript manipulando elementos")
	fmt.Println("JavaScript adicionando interatividade:")
	fmt.Println()

	fmt.Println("  // script.js")
	fmt.Println("  document.getElementById(\"botao\").addEventListener(\"click\", function() {")
	fmt.Println("      const titulo = document.getElementById(\"titulo\");")
	fmt.Println("      titulo.textContent = \"Título Alterado!\";")
	fmt.Println("      titulo.style.color = \"red\";")
	fmt.Println("  });")
	fmt.Println()

	fmt.Println("Exemplo 4: Fluxo completo de interação")
	fmt.Println("Como tudo funciona junto quando usuário interage:")
	fmt.Println()

	fmt.Println("  1. Usuário vê botão estilizado (CSS)")
	fmt.Println("  2. Usuário clica no botão")
	fmt.Println("  3. JavaScript detecta o clique (evento)")
	fmt.Println("  4. JavaScript modifica o HTML (DOM)")
	fmt.Println("  5. CSS aplica novos estilos se necessário")
	fmt.Println("  6. Navegador re-renderiza a página")
	fmt.Println()

	fmt.Println("Exemplo 5: Ordem de carregamento")
	fmt.Println("Ordem correta de carregamento dos recursos:")
	fmt.Println()

	fmt.Println("  <head>")
	fmt.Println("      <!-- CSS deve estar no <head> para carregar primeiro -->")
	fmt.Println("      <link rel=\"stylesheet\" href=\"estilo.css\">")
	fmt.Println("  </head>")
	fmt.Println("  <body>")
	fmt.Println("      <!-- Conteúdo HTML -->")
	fmt.Println("      <!-- JavaScript deve estar antes de </body> -->")
	fmt.Println("      <script src=\"script.js\"></script>")
	fmt.Println("  </body>")
	fmt.Println()

	fmt.Println("Vantagens da separação:")
	fmt.Println("  ✓ HTML focado em estrutura")
	fmt.Println("  ✓ CSS focado em apresentação")
	fmt.Println("  ✓ JavaScript focado em comportamento")
	fmt.Println("  ✓ Facilita manutenção e reutilização")
	fmt.Println("  ✓ Permite cache separado de recursos")
	fmt.Println()

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - HTML define estrutura, CSS define aparência, JS define comportamento")
	fmt.Println("  - CSS deve estar no <head> para evitar flash de conteúdo não estilizado")
	fmt.Println("  - JavaScript deve estar antes de </body> ou usar defer")
	fmt.Println("  - Use arquivos externos (não inline) para melhor organização")
	fmt.Println("  - Navegador faz requisições separadas para cada arquivo")
	fmt.Println("  - Ordem de carregamento afeta renderização")
	fmt.Println("  - JavaScript pode modificar HTML e CSS dinamicamente")
	fmt.Println("  - Sempre teste em diferentes navegadores")
	fmt.Println()
}
