package web

import (
	"fmt"
)

// DemonstrarJavaScriptBasico demonstra os conceitos básicos de JavaScript
func DemonstrarJavaScriptBasico() {
	fmt.Println("--- JAVASCRIPT BÁSICO ---")
	fmt.Println("JavaScript é uma linguagem de programação que adiciona")
	fmt.Println("interatividade e comportamento dinâmico às páginas web.")
	fmt.Println()

	fmt.Println("Por que usar JavaScript?")
	fmt.Println("  - Adiciona interatividade às páginas")
	fmt.Println("  - Manipula o DOM (Document Object Model)")
	fmt.Println("  - Responde a eventos do usuário")
	fmt.Println("  - Valida formulários no cliente")
	fmt.Println("  - Cria experiências dinâmicas")
	fmt.Println("  - Executa no navegador do cliente")
	fmt.Println()

	fmt.Println("Como vincular JavaScript ao HTML:")
	fmt.Println("  1. Arquivo externo (recomendado):")
	fmt.Println("     <script src=\"script.js\"></script>")
	fmt.Println("  2. Dentro do HTML com <script>:")
	fmt.Println("     <script> console.log('Olá'); </script>")
	fmt.Println("  3. Como atributo inline (evitar):")
	fmt.Println("     <button onclick=\"alert('Clique')\">Botão</button>")
	fmt.Println()

	fmt.Println("Exemplo 1: Variáveis e tipos")
	fmt.Println("Declarando variáveis em JavaScript:")
	fmt.Println()

	fmt.Println("  // let - variável que pode ser reatribuída")
	fmt.Println("  let nome = \"João\";")
	fmt.Println("  nome = \"Maria\";")
	fmt.Println()
	fmt.Println("  // const - constante (não pode ser reatribuída)")
	fmt.Println("  const idade = 30;")
	fmt.Println()
	fmt.Println("  // var - antiga forma (evitar)")
	fmt.Println("  var antiga = \"não usar\";")
	fmt.Println()
	fmt.Println("  // Tipos básicos")
	fmt.Println("  let texto = \"String\";")
	fmt.Println("  let numero = 42;")
	fmt.Println("  let booleano = true;")
	fmt.Println("  let array = [1, 2, 3];")
	fmt.Println("  let objeto = { nome: \"João\", idade: 30 };")
	fmt.Println()

	fmt.Println("Exemplo 2: Funções básicas")
	fmt.Println("Criando e usando funções:")
	fmt.Println()

	fmt.Println("  // Função declarada")
	fmt.Println("  function saudar(nome) {")
	fmt.Println("      return \"Olá, \" + nome;")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  // Função anônima")
	fmt.Println("  const multiplicar = function(a, b) {")
	fmt.Println("      return a * b;")
	fmt.Println("  };")
	fmt.Println()
	fmt.Println("  // Arrow function")
	fmt.Println("  const somar = (a, b) => a + b;")
	fmt.Println()

	fmt.Println("Exemplo 3: Manipulação do DOM")
	fmt.Println("Acessando e modificando elementos HTML:")
	fmt.Println()

	fmt.Println("  // Selecionar elemento por ID")
	fmt.Println("  const elemento = document.getElementById(\"meuId\");")
	fmt.Println()
	fmt.Println("  // Selecionar elemento por classe")
	fmt.Println("  const elementos = document.getElementsByClassName(\"minhaClasse\");")
	fmt.Println()
	fmt.Println("  // Selecionar elemento por seletor CSS")
	fmt.Println("  const elemento2 = document.querySelector(\".classe\");")
	fmt.Println()
	fmt.Println("  // Modificar conteúdo")
	fmt.Println("  elemento.textContent = \"Novo texto\";")
	fmt.Println("  elemento.innerHTML = \"<strong>HTML</strong>\";")
	fmt.Println()
	fmt.Println("  // Modificar atributos")
	fmt.Println("  elemento.setAttribute(\"class\", \"nova-classe\");")
	fmt.Println("  elemento.style.color = \"blue\";")
	fmt.Println()

	fmt.Println("Exemplo 4: Eventos básicos")
	fmt.Println("Respondendo a ações do usuário:")
	fmt.Println()

	fmt.Println("  // Evento de clique")
	fmt.Println("  document.getElementById(\"botao\").addEventListener(\"click\", function() {")
	fmt.Println("      alert(\"Botão clicado!\");")
	fmt.Println("  });")
	fmt.Println()
	fmt.Println("  // Evento de entrada em campo")
	fmt.Println("  document.getElementById(\"input\").addEventListener(\"input\", function(evento) {")
	fmt.Println("      console.log(\"Valor:\", evento.target.value);")
	fmt.Println("  });")
	fmt.Println()
	fmt.Println("  // Evento de submit de formulário")
	fmt.Println("  document.getElementById(\"formulario\").addEventListener(\"submit\", function(evento) {")
	fmt.Println("      evento.preventDefault(); // Previne envio padrão")
	fmt.Println("      console.log(\"Formulário enviado\");")
	fmt.Println("  });")
	fmt.Println()

	fmt.Println("Exemplo 5: Validação básica")
	fmt.Println("Validando dados antes de enviar:")
	fmt.Println()

	fmt.Println("  function validarFormulario() {")
	fmt.Println("      const nome = document.getElementById(\"nome\").value;")
	fmt.Println("      if (nome === \"\") {")
	fmt.Println("          alert(\"Nome é obrigatório\");")
	fmt.Println("          return false;")
	fmt.Println("      }")
	fmt.Println("      return true;")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - Use 'let' ou 'const' (evite 'var')")
	fmt.Println("  - Sempre use 'const' se o valor não mudar")
	fmt.Println("  - Scripts devem estar antes de </body> ou usar defer")
	fmt.Println("  - Sempre valide dados no servidor também")
	fmt.Println("  - Use addEventListener em vez de atributos inline")
	fmt.Println("  - Console.log() é útil para depuração")
	fmt.Println("  - JavaScript executa no navegador do cliente")
	fmt.Println("  - Código JavaScript é visível para o usuário")
	fmt.Println()
}
