package http

import (
	"fmt"
)

// DemonstrarRotasHandlers demonstra organização de rotas e handlers
func DemonstrarRotasHandlers() {
	fmt.Println("--- ROTAS E HANDLERS ---")
	fmt.Println("Rotas definem os caminhos que o servidor responde.")
	fmt.Println("Handlers são funções que processam requisições para essas rotas.\n")

	fmt.Println("Por que organizar rotas e handlers?")
	fmt.Println("  - Facilita manutenção e leitura do código")
	fmt.Println("  - Permite reutilização de handlers")
	fmt.Println("  - Melhora organização do projeto")
	fmt.Println("  - Facilita adicionar novas rotas")
	fmt.Println("  - Separa lógica de negócio da configuração HTTP\n")

	fmt.Println("Exemplo 1: Handlers como funções separadas")
	fmt.Println("Organizando handlers em funções nomeadas:\n")

	fmt.Println("  func handlerInicial(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Página inicial\")")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func handlerSobre(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Página sobre\")")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func main() {")
	fmt.Println("      http.HandleFunc(\"/\", handlerInicial)")
	fmt.Println("      http.HandleFunc(\"/sobre\", handlerSobre)")
	fmt.Println("      http.ListenAndServe(\":8080\", nil)")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 2: Rotas com parâmetros simples")
	fmt.Println("Extraindo informações da URL manualmente:\n")

	fmt.Println("  func handlerUsuario(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      caminho := requisicao.URL.Path")
	fmt.Println("      partes := strings.Split(caminho, \"/\")")
	fmt.Println("      if len(partes) >= 3 {")
	fmt.Println("          idUsuario := partes[2]")
	fmt.Println("          fmt.Fprintf(escritorResposta, \"ID do usuário: %s\", idUsuario)")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/usuarios/\", handlerUsuario)")
	fmt.Println("  // Uso: /usuarios/123\n")

	fmt.Println("Exemplo 3: Organizando handlers por funcionalidade")
	fmt.Println("Agrupando handlers relacionados:\n")

	fmt.Println("  func configurarRotasUsuarios() {")
	fmt.Println("      http.HandleFunc(\"/usuarios\", handlerListarUsuarios)")
	fmt.Println("      http.HandleFunc(\"/usuarios/criar\", handlerCriarUsuario)")
	fmt.Println("      http.HandleFunc(\"/usuarios/atualizar\", handlerAtualizarUsuario)")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func configurarRotasProdutos() {")
	fmt.Println("      http.HandleFunc(\"/produtos\", handlerListarProdutos)")
	fmt.Println("      http.HandleFunc(\"/produtos/criar\", handlerCriarProduto)")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func main() {")
	fmt.Println("      configurarRotasUsuarios()")
	fmt.Println("      configurarRotasProdutos()")
	fmt.Println("      http.ListenAndServe(\":8080\", nil)")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 4: Handler com verificação de método")
	fmt.Println("Um handler que aceita múltiplos métodos:\n")

	fmt.Println("  func handlerFlexivel(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      switch requisicao.Method {")
	fmt.Println("      case http.MethodGet:")
	fmt.Println("          fmt.Fprintf(escritorResposta, \"Listando dados\")")
	fmt.Println("      case http.MethodPost:")
	fmt.Println("          fmt.Fprintf(escritorResposta, \"Criando dados\")")
	fmt.Println("      default:")
	fmt.Println("          http.Error(escritorResposta, \"Método não permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/dados\", handlerFlexivel)\n")

	fmt.Println("Exemplo 5: Handler com validação básica")
	fmt.Println("Validando requisições antes de processar:\n")

	fmt.Println("  func handlerValidado(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      if requisicao.Method != http.MethodPost {")
	fmt.Println("          http.Error(escritorResposta, \"Apenas POST permitido\", http.StatusMethodNotAllowed)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      if requisicao.ContentLength == 0 {")
	fmt.Println("          http.Error(escritorResposta, \"Body vazio\", http.StatusBadRequest)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Requisição válida\")")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/validar\", handlerValidado)\n")

	fmt.Println("Exemplo 6: Handler que retorna diferentes formatos")
	fmt.Println("Respondendo conforme Accept header:\n")

	fmt.Println("  func handlerFormatos(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      accept := requisicao.Header.Get(\"Accept\")")
	fmt.Println("      if strings.Contains(accept, \"application/json\") {")
	fmt.Println("          escritorResposta.Header().Set(\"Content-Type\", \"application/json\")")
	fmt.Println("          fmt.Fprintf(escritorResposta, `{\"mensagem\":\"JSON\"}`)")
	fmt.Println("      } else {")
	fmt.Println("          fmt.Fprintf(escritorResposta, \"Texto simples\")")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/formatos\", handlerFormatos)\n")

	fmt.Println("Exemplo 7: Handler com tratamento de erro")
	fmt.Println("Tratando erros adequadamente:\n")

	fmt.Println("  func handlerComErro(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      dados, erro := processarDados(requisicao)")
	fmt.Println("      if erro != nil {")
	fmt.Println("          http.Error(escritorResposta, erro.Error(), http.StatusBadRequest)")
	fmt.Println("          return")
	fmt.Println("      }")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Dados processados: %s\", dados)")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/processar\", handlerComErro)\n")

	fmt.Println("Boas práticas de organização:")
	fmt.Println("  ✓ Separe handlers em funções nomeadas")
	fmt.Println("  ✓ Agrupe rotas relacionadas")
	fmt.Println("  ✓ Use funções de configuração para organizar rotas")
	fmt.Println("  ✓ Valide requisições no início dos handlers")
	fmt.Println("  ✓ Retorne erros apropriados com status codes")
	fmt.Println("  ✓ Mantenha handlers simples e focados\n")

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - Handlers devem ser funções com assinatura específica")
	fmt.Println("  - Sempre valide método HTTP antes de processar")
	fmt.Println("  - Use return após http.Error() para parar execução")
	fmt.Println("  - Organize rotas por funcionalidade")
	fmt.Println("  - Mantenha handlers pequenos e focados")
	fmt.Println("  - Trate erros adequadamente")
	fmt.Println("  - Use defer para garantir limpeza de recursos")
	fmt.Println("  - Headers devem ser definidos antes de escrever no body")
	fmt.Println()
}
