package http

import (
	"fmt"
)

// DemonstrarServidorNativo demonstra como criar servidor HTTP usando apenas net/http padrão
func DemonstrarServidorNativo() {
	fmt.Println("--- SERVIDOR HTTP NATIVO ---")
	fmt.Println("Go possui um pacote padrão 'net/http' que permite criar servidores HTTP")
	fmt.Println("sem necessidade de bibliotecas externas.\n")

	fmt.Println("Por que usar net/http padrão?")
	fmt.Println("  - Já vem com a linguagem, sem dependências externas")
	fmt.Println("  - Simples e direto para casos básicos")
	fmt.Println("  - Performance excelente")
	fmt.Println("  - Controle total sobre o comportamento")
	fmt.Println("  - Ideal para aprender os fundamentos\n")

	fmt.Println("Exemplo 1: Servidor HTTP mais simples possível")
	fmt.Println("Criando um servidor que responde em todas as rotas:\n")

	fmt.Println("  package main")
	fmt.Println("  import (")
	fmt.Println("      \"fmt\"")
	fmt.Println("      \"net/http\"")
	fmt.Println("  )")
	fmt.Println()
	fmt.Println("  func main() {")
	fmt.Println("      http.HandleFunc(\"/\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("          fmt.Fprintf(escritorResposta, \"Olá, mundo!\")")
	fmt.Println("      })")
	fmt.Println("      http.ListenAndServe(\":8080\", nil)")
	fmt.Println("  }\n")

	fmt.Println("Explicação:")
	fmt.Println("  - HandleFunc: registra uma função para tratar requisições em uma rota")
	fmt.Println("  - ResponseWriter: usado para escrever a resposta HTTP")
	fmt.Println("  - Request: contém informações da requisição recebida")
	fmt.Println("  - ListenAndServe: inicia o servidor na porta especificada\n")

	fmt.Println("Exemplo 2: Múltiplas rotas")
	fmt.Println("Definindo diferentes handlers para diferentes rotas:\n")

	fmt.Println("  http.HandleFunc(\"/\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Página inicial\")")
	fmt.Println("  })")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/sobre\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Página sobre\")")
	fmt.Println("  })")
	fmt.Println()
	fmt.Println("  http.HandleFunc(\"/contato\", func(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Página de contato\")")
	fmt.Println("  })")
	fmt.Println()
	fmt.Println("  http.ListenAndServe(\":8080\", nil)\n")

	fmt.Println("Exemplo 3: Handler como função separada")
	fmt.Println("Organizando handlers em funções nomeadas:\n")

	fmt.Println("  func handlerInicial(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Página inicial\")")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func handlerSobre(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, \"Página sobre\")")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func main() {")
	fmt.Println("      http.HandleFunc(\"/\", handlerInicial)")
	fmt.Println("      http.HandleFunc(\"/sobre\", handlerSobre)")
	fmt.Println("      http.ListenAndServe(\":8080\", nil)")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 4: Handler usando interface")
	fmt.Println("Criando um tipo que implementa a interface Handler:\n")

	fmt.Println("  type MeuHandler struct {")
	fmt.Println("      mensagem string")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func (handler MeuHandler) ServeHTTP(escritorResposta http.ResponseWriter, requisicao *http.Request) {")
	fmt.Println("      fmt.Fprintf(escritorResposta, handler.mensagem)")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  func main() {")
	fmt.Println("      handler := MeuHandler{mensagem: \"Olá do handler\"}")
	fmt.Println("      http.Handle(\"/custom\", handler)")
	fmt.Println("      http.ListenAndServe(\":8080\", nil)")
	fmt.Println("  }\n")

	fmt.Println("Exemplo 5: Usando ServeMux para melhor organização")
	fmt.Println("ServeMux permite criar múltiplos roteadores:\n")

	fmt.Println("  func main() {")
	fmt.Println("      mux := http.NewServeMux()")
	fmt.Println("      mux.HandleFunc(\"/\", handlerInicial)")
	fmt.Println("      mux.HandleFunc(\"/sobre\", handlerSobre)")
	fmt.Println("      http.ListenAndServe(\":8080\", mux)")
	fmt.Println("  }\n")

	fmt.Println("Vantagens do servidor nativo:")
	fmt.Println("  ✓ Sem dependências externas")
	fmt.Println("  ✓ Simples e direto")
	fmt.Println("  ✓ Performance excelente")
	fmt.Println("  ✓ Ideal para aprender fundamentos")
	fmt.Println("  ✓ Controle total sobre comportamento\n")

	fmt.Println("Quando usar servidor nativo:")
	fmt.Println("  - Aprendizado dos fundamentos HTTP")
	fmt.Println("  - APIs simples e diretas")
	fmt.Println("  - Quando não precisa de recursos avançados")
	fmt.Println("  - Quando quer evitar dependências externas\n")

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - ListenAndServe bloqueia a execução (use goroutine se necessário)")
	fmt.Println("  - Sempre trate erros retornados por ListenAndServe")
	fmt.Println("  - Use defer para fechar recursos (body, conexões)")
	fmt.Println("  - ResponseWriter escreve diretamente na conexão")
	fmt.Println("  - Request.Body deve ser lido e fechado quando usado")
	fmt.Println("  - Headers devem ser definidos antes de escrever no body")
	fmt.Println("  - Use http.Error() para retornar erros HTTP")
	fmt.Println()
}
