package web

import (
	"fmt"
)

// DemonstrarCSSBasico demonstra os conceitos básicos de CSS
func DemonstrarCSSBasico() {
	fmt.Println("--- CSS BÁSICO ---")
	fmt.Println("CSS (Cascading Style Sheets) é usado para estilizar páginas HTML.")
	fmt.Println("Ele controla a aparência visual dos elementos.")
	fmt.Println()

	fmt.Println("Por que usar CSS?")
	fmt.Println("  - Separa apresentação visual da estrutura HTML")
	fmt.Println("  - Permite reutilização de estilos")
	fmt.Println("  - Facilita manutenção e atualização")
	fmt.Println("  - Permite criar layouts responsivos")
	fmt.Println("  - Melhora experiência do usuário")
	fmt.Println()

	fmt.Println("Como vincular CSS ao HTML:")
	fmt.Println("  1. Arquivo externo (recomendado):")
	fmt.Println("     <link rel=\"stylesheet\" href=\"estilo.css\">")
	fmt.Println("  2. Dentro do <head> com <style>:")
	fmt.Println("     <style> h1 { color: blue; } </style>")
	fmt.Println("  3. Estilo inline (evitar):")
	fmt.Println("     <h1 style=\"color: blue;\">Título</h1>")
	fmt.Println()

	fmt.Println("Exemplo 1: Seletores básicos")
	fmt.Println("Diferentes formas de selecionar elementos:")
	fmt.Println()

	fmt.Println("  /* Seletor de elemento */")
	fmt.Println("  h1 {")
	fmt.Println("      color: blue;")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  /* Seletor de classe */")
	fmt.Println("  .destaque {")
	fmt.Println("      background-color: yellow;")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  /* Seletor de ID */")
	fmt.Println("  #cabecalho {")
	fmt.Println("      font-size: 24px;")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  /* Seletor combinado */")
	fmt.Println("  div.container {")
	fmt.Println("      margin: 10px;")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("Exemplo 2: Propriedades básicas")
	fmt.Println("Propriedades CSS mais comuns:")
	fmt.Println()

	fmt.Println("  /* Cores e texto */")
	fmt.Println("  color: blue;              /* Cor do texto */")
	fmt.Println("  background-color: white;  /* Cor de fundo */")
	fmt.Println("  font-size: 16px;          /* Tamanho da fonte */")
	fmt.Println("  font-family: Arial;       /* Família da fonte */")
	fmt.Println("  text-align: center;      /* Alinhamento do texto */")
	fmt.Println()
	fmt.Println("  /* Espaçamento */")
	fmt.Println("  margin: 10px;            /* Espaço externo */")
	fmt.Println("  padding: 5px;            /* Espaço interno */")
	fmt.Println()
	fmt.Println("  /* Dimensões */")
	fmt.Println("  width: 100%;             /* Largura */")
	fmt.Println("  height: 200px;           /* Altura */")
	fmt.Println()

	fmt.Println("Exemplo 3: Box Model")
	fmt.Println("Entendendo como elementos ocupam espaço:")
	fmt.Println()

	fmt.Println("  .caixa {")
	fmt.Println("      width: 200px;        /* Largura do conteúdo */")
	fmt.Println("      padding: 20px;      /* Espaço interno */")
	fmt.Println("      border: 2px solid black;  /* Borda */")
	fmt.Println("      margin: 10px;       /* Espaço externo */")
	fmt.Println("  }")
	fmt.Println("  /* Largura total = width + padding + border + margin */")
	fmt.Println()

	fmt.Println("Exemplo 4: Layout básico")
	fmt.Println("Criando layout simples com CSS:")
	fmt.Println()

	fmt.Println("  .container {")
	fmt.Println("      display: flex;")
	fmt.Println("      justify-content: center;")
	fmt.Println("      align-items: center;")
	fmt.Println("  }")
	fmt.Println()
	fmt.Println("  .coluna {")
	fmt.Println("      width: 50%;")
	fmt.Println("      float: left;")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("Exemplo 5: Responsividade básica")
	fmt.Println("Media queries para diferentes tamanhos de tela:")
	fmt.Println()

	fmt.Println("  @media (max-width: 600px) {")
	fmt.Println("      .coluna {")
	fmt.Println("          width: 100%;")
	fmt.Println("      }")
	fmt.Println("  }")
	fmt.Println()

	fmt.Println("⚠️  IMPORTANTE:")
	fmt.Println("  - Use arquivo CSS externo (não inline)")
	fmt.Println("  - Seletor de ID (#) é mais específico que classe (.)")
	fmt.Println("  - Classe (.) é mais específico que elemento")
	fmt.Println("  - CSS é aplicado em cascata (último vence)")
	fmt.Println("  - Use unidades relativas (%, em, rem) quando possível")
	fmt.Println("  - Valide CSS antes de publicar")
	fmt.Println("  - Use nomes descritivos para classes e IDs")
	fmt.Println("  - Evite !important a menos que necessário")
	fmt.Println()
}
